Adding getToken and getLocker methods
bsm/redis-lock pull request #21
Opened 2019-06-22 02:03 UTC by kshamajain99

In our project we have following use cases:

In our project we have used instance_id as token prefix. Later, we want to get tokenPrefix so that we can tell which instance has locked a resource by getting that instance_id. Hence, I have added a getToken() method.

We want the ability to get locker object from lock key. So that we can getToken from that locker object.

2019-06-22 02:04 UTC, kshamajain99 commented
@dim please have a look at this PR.

2019-06-24 08:58 UTC, dim requested changes

2019-06-24 08:58 UTC, dim commented on lock.go
> +	return l.token
sorry, but this is not safe for concurrent access

2019-06-24 08:58 UTC, dim commented on lock.go
> +func GetLocker(client *redis.ClusterClient, key string, opts *Options) (*Locker, error) {
how is this different from `Obtain`?

2019-06-24 11:13 UTC, bsm commented
Please see https://github.com/bsm/redislock instead

2019-06-24 11:13 UTC, closed without merging